<a href="https://colab.research.google.com/github/AnkitaAnalytics/Python_Basics/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

From a given array, extract all the elements which are greater than 'm' and less than 'n'. NOTE: 'm' and 'n' are integer values provided as input.



**Input format:**

A list of integers on line one

Integer 'm' on line two

Integer 'n' on line three



**Output format:**

1-D array containing integers greater than 'm' and smaller than 'n'.

In [ ]:
import ast
input_list=ast.literal_eval(input("Enter the list "))
m=int(input("Enter integer m "))
n=int(input("Enter interger n "))

import numpy as np
array_1 = np.array(input_list)
final_array = np.array([item for item in array_1 if m < item <n])
print(final_array)

Enter the list [ 1, 5, 9, 12, 15, 7, 12, 9 ] 
Enter integer m 6
Enter interger n 12
[9 7 9]


**Question:** Create an array of the first 10 multiples of 5 using the 'arange' function.

In [ ]:
a = np.arange(5,51,5)
print ("The array of the first 10 multiples of 5 is: ", a)

The array of the first 10 multiples of 5 is:  [ 5 10 15 20 25 30 35 40 45 50]


**Checkerboard Matrix**
Description
Given an even integer ‘n’, create an ‘n*n’ checkerboard matrix with the values 0 and 1, using the tile function.



Format:

Input: A single even integer 'n'.

Output: An 'n*n' NumPy array in checkerboard format.

In [ ]:
n = int(input("Enter the value of n "))
import numpy as np

#creating n*n matrix containing zeros

a = np.zeros((n,n),dtype = int)
print (a)

Enter the value of n 3
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
b = np.tile(a,1)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

**Question** For the given data calculate the following:-
1. How many students completed more than 15 modules ?
2. what is the average quiz score?
3. How many students scored above 90 in the quiz?
4. Due to a system error, the scores of the first five students in the quiz_scores array were recorded incorrectly. Their correct scores are as follows: correct_scores = np.array([82, 88, 76, 95, 90]) . Replace the scores with correct scores
5. What percentage of students scored below 80 in the quiz?

In [ ]:
import numpy as np

#data for student performance
modules_completed = np.array([12, 15, 18, 20, 14, 16, 22, 10, 13, 17, 19, 21, 14, 12, 16, 18, 20, 14, 16, 19])
quiz_scores = np.array([85, 90, 78, 92, 88, 76, 95, 80, 89, 94, 81, 87, 93, 79, 91, 84, 88, 75, 82, 96])

In [ ]:
#students who completed more than 15 modules
m= np.sum(modules_completed > 15)
print ("students who completed more than 15 modules are ", m)

students who completed more than 15 modules are  12


In [ ]:
#average quiz scores

n= np.mean(quiz_scores)
print ("The average quiz scores is ", n)

The average quiz scores is  86.15


In [ ]:
#students who scored above 90

students_above90= np.sum(quiz_scores > 90)
print ("students who scored above 90 are ", students_above90)

students who scored above 90 are  6


In [ ]:
#adding correct scores
correct_scores = np.array([82, 88, 76, 95, 90])
quiz_scores[:5] = correct_scores
print(quiz_scores)

[82 88 76 95 90 76 95 80 89 94 81 87 93 79 91 84 88 75 82 96]


In [ ]:
# percentage of students who scored below 80 in quiz
students_below80 = (np.sum(quiz_scores < 80) / len(quiz_scores)) * 100
print("Percentage of students who scored below 80 in quiz:", students_below80)

Percentage of students who scored below 80 in quiz: 20.0
